version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /home/pi/esp-camera/Server/uploads:/app/uploads
    environment:
      FLASK_ENV: development
  frontend:
    build: ./frontend
    ports:
      - "80:3000"
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend  
    